services:
    postgres:
        image: postgres:latest
        container_name: postgres_container
        environment:
            POSTGRES_USER: zabbix
            POSTGRES_PASSWORD: zabbixpwd
            POSTGRES_DB: zabbix
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 256M
        command: >
            postgres -c max_connections=1000
                -c shared_buffers=256MB
                -c effective_cache_size=768MB
                -c maintenance_work_mem=64MB
                -c checkpoint_completion_target=0.7
                -c wal_buffers=16MB
                -c default_statistics_target=100
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        tty: true
        stdin_open: true
        networks:
            - zabbix-network

    zabbix-server-pgsql:
        image: zabbix/zabbix-server-pgsql
        container_name: some-zabbix-server-pgsql
        environment:
            DB_SERVER_HOST: 127.0.0.1
            DB_SERVER_PORT: 5432
            POSTGRES_USER: zabbix
            POSTGRES_PASSWORD: zabbixpwd
        init: true
        networks:
            - zabbix-network

    zabbix-agent:
        image: zabbix/zabbix-agent
        container_name: some-zabbix-agent
        environment:
            ZBX_HOSTNAME: zabbix
            ZBX_SERVER_HOST: 127.0.0.1
        init: true
        networks:
            - zabbix-network

    zabbix-web-nginx-pgsql:
        image: zabbix/zabbix-web-nginx-pgsql
        container_name: some-zabbix-web-nginx-pgsql
        environment:
            DB_SERVER_HOST: 127.0.0.1
            POSTGRES_USER: zabbix
            POSTGRES_PASSWORD: zabbixpwd
            ZBX_SERVER_HOST: 127.0.0.1
            PHP_TZ: Europe/Moscow
        ports:
            - "80:8080"
        networks:
            - zabbix-network
      
volumes:
  pgdata:
    driver: local

networks:
    zabbix-network:
        driver: bridge
